language: generic
os: linux

install:
- cd ci/
- source texlive.sh
- cd ..

cache:
  directories:
  - /tmp/texlive
  - $HOME/.texlive
  - /tmp/tlpkg
  - doc/latex/pgfplots/figures/expensiveexamples
  - doc/latex/pgfplots/gnuplot

addons:
  apt:
    packages:
    - gnuplot
    - realpath

before_script:
- git fetch --unshallow --tags
- bash scripts/pgfplots/pgfplotsrevisionfile.sh
- cat tex/generic/pgfplots/pgfplots.revision.tex

script: |
  cd doc/latex/pgfplots
  while : ; do
    make -j $(nproc) LATEX="$engine -shell-escape -halt-on-error -interaction=nonstopmode"
    grep -q -E "(There were undefined references|Rerun to get (cross-references|the bars) right)" *.log || break
    [ "$(( thisrun=$(( thisrun + 1 )) ))" -lt 5 ] || { echo "Reruns exceeded"; exit 1; }
  done
  cd -

jobs:
  include:
  - env: engine=lualatex
  - env: engine=pdflatex
