language: generic
os: linux

install:
- cd ci/
- source texlive.sh
- cd ..

cache:
  directories:
  - /tmp/texlive
  - $HOME/.texlive
  - /tmp/tlpkg
  - doc/latex/pgfplots/figures/expensiveexamples
  - doc/latex/pgfplots/gnuplot

addons:
  apt:
    packages:
    - gnuplot
    - realpath

before_script:
- git fetch --unshallow --tags
- bash scripts/pgfplots/pgfplotsrevisionfile.sh
- cat tex/generic/pgfplots/pgfplots.revision.tex

script: |
  set -e
  cd doc/latex/pgfplots
  while : ; do
    make -j $(nproc) LATEX="$engine -shell-escape -halt-on-error -interaction=nonstopmode"
    grep -q -E "(There were undefined references|Rerun to get (cross-references|the bars) right)" *.log || break
    [ "$(( thisrun=$(( thisrun + 1 )) ))" -lt 5 ] || { echo "Reruns exceeded"; exit 1; }
  done
  cd -

after_success: |
  set -e
  mkdir -pv /tmp/gh-pages
  cp -v doc/latex/pgfplots/*.pdf /tmp/gh-pages
  make -C .. -f pgfplots/scripts/pgfplots/Makefile.pgfplots_release_sourceforge

jobs:
  include:
  - env: engine=lualatex
  - env: engine=pdflatex

deploy:
- provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  committer_from_gh: true
  local_dir: /tmp/gh-pages
  on:
    branch: master
    tags: false
    condition: $engine = lualatex
- provider: releases
  skip_cleanup: true
  token: $GH_TOKEN
  file_glob: true
  file:
  - ../pgfplots_*
  overwrite: true
  on:
    tags: true
    condition: $engine = lualatex
