language: generic
os: linux

install:
- cd ci/
- source texlive.sh
- cd ..

cache:
  directories:
  - /tmp/texlive
  - $HOME/.texlive
  - /tmp/tlpkg

addons:
  apt:
    packages:
    - gnuplot
    - realpath

before_script:
- git fetch --unshallow --tags
- bash scripts/pgfplots/pgfplotsrevisionfile.sh
- cat tex/generic/pgfplots/pgfplots.revision.tex

jobs:
  include:
  - env: engine=lualatex
    script:
    - cd doc/latex/pgfplots
    - make -j $(nproc) LATEX="lualatex -shell-escape -halt-on-error -interaction=nonstopmode"

  - env: engine=pdflatex
    script:
    - cd doc/latex/pgfplots
    - make -j $(nproc) LATEX="pdflatex -shell-escape -halt-on-error -interaction=nonstopmode"

